lines = [
    ".p2align 4",
    ".global PantheonShader",
    "PantheonShader:",
    "  NOP", "\tLQ vf01, 2(vi00)",
    "  NOP", "\tLQ vf02, 3(vi00)",
    "  NOP", "\tLQ vf03, 4(vi00)",
    "  NOP", "\tLQ vf04, 5(vi00)",
    "  NOP", "\tLQ vf05, 1(vi00)",
    "  NOP", "\tLQ vf06, 0(vi00)",
    "  NOP", "\tNOP",
    "  NOP", "\tSQ vf06, 64(vi00)",
    "  NOP", "\tXITOP vi01",
    "  NOP", "\tIADDIU vi02, vi00, 6",
    "  NOP", "\tIADDIU vi03, vi00, 65",
    "VertexLoop:",
    "  NOP", "\tIBEQ vi01, vi00, EndLoop",
    "  NOP", "\tIADDI vi01, vi01, -1",
    "  NOP", "\tLQ vf08, 0(vi02)",
    "  NOP", "\tLQ vf09, 1(vi02)",
    "  NOP", "\tIADDI vi02, vi02, 2",
    "  NOP", "\tNOP",
    "  MUL.xyzw vf10, vf01, vf08x", "\tNOP",
    "  MADD.xyzw vf10, vf02, vf08y", "\tNOP",
    "  MADD.xyzw vf10, vf03, vf08z", "\tNOP",
    "  MADD.xyzw vf10, vf04, vf08w", "\tNOP",
    "  NOP", "\tDIV Q, vf00w, vf10w",
    "  NOP", "\tWAITQ",
    "  MUL.xyzw vf10, vf10, Q", "\tNOP",
    "  MADD.xyzw vf10, vf05, vf00w", "\tNOP",
    "  FTOI4.xyzw vf10, vf10", "\tNOP",
    "  NOP", "\tSQ vf09, 0(vi03)",
    "  NOP", "\tSQ vf10, 1(vi03)",
    "  NOP", "\tIADDI vi03, vi03, 2",
    "  NOP", "\tB VertexLoop",
    "  NOP", "\tNOP",
    "EndLoop:",
    "  NOP", "\tIADDIU vi04, vi00, 64",
    "  NOP", "\tXGKICK vi04",
    "  NOP[e]", "\tNOP",
    "  NOP", "\tNOP",
    ".global PantheonShaderEnd",
    "PantheonShaderEnd:"
]
with open('shader.vsm', 'w') as f:
    f.write('\n'.join(lines) + '\n')
